/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamingplatform;

import java.sql.*;
import streamingConectDB.ConectareBD;

import java.awt.Color;
import java.awt.Panel;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author roxana
 */
public class inregistrare extends javax.swing.JFrame {

   
    public inregistrare() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        atentie.setVisible(false);
        abonamente.setVisible(false);
        mesaj_err_abonament.setVisible(false);
        plati.setVisible(false);
        mesaj_err_plata.setVisible(false);
        
       java.util.Date utilDate = new java.util.Date();
       java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
       datadenastere.setDate(sqlDate);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raspuns_plata = new javax.swing.ButtonGroup();
        baraXMinMax = new java.awt.Panel();
        iconXMinMax = new java.awt.Panel();
        butonX = new java.awt.Panel();
        Xmouse = new javax.swing.JLabel();
        butonMax = new java.awt.Panel();
        Maxmouse = new javax.swing.JLabel();
        butonMin = new java.awt.Panel();
        Minmouse = new javax.swing.JLabel();
        inregistrareUser = new java.awt.Panel();
        backgroundL = new java.awt.Panel();
        imag = new javax.swing.JLabel();
        backgroundR = new java.awt.Panel();
        inregistrare_abonamente_plati = new java.awt.Panel();
        plati = new javax.swing.JPanel();
        plata_abonament = new javax.swing.JLabel();
        backcabonamente = new javax.swing.JPanel();
        buton_backcabonamente = new javax.swing.JButton();
        cont_inregistrat = new javax.swing.JPanel();
        buton_inregistrare = new javax.swing.JButton();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        copie_suma = new javax.swing.JLabel();
        rb_nu = new javax.swing.JRadioButton();
        rb_da = new javax.swing.JRadioButton();
        copie_abonament = new javax.swing.JPanel();
        copie_tip = new javax.swing.JLabel();
        copie_pret = new javax.swing.JLabel();
        copie_plataluna = new javax.swing.JLabel();
        copie_lei = new javax.swing.JLabel();
        copie_descriere = new javax.swing.JTextArea();
        mesaj_err_plata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        abonamente = new javax.swing.JPanel();
        alegeabonament = new javax.swing.JLabel();
        abonament_basic = new javax.swing.JPanel();
        label_basic = new javax.swing.JLabel();
        label_pret_b = new javax.swing.JLabel();
        label_suma_b = new javax.swing.JLabel();
        lei_b = new javax.swing.JLabel();
        descriere_basic = new javax.swing.JTextArea();
        abonament_standard = new javax.swing.JPanel();
        label_standard = new javax.swing.JLabel();
        label_pret_s = new javax.swing.JLabel();
        label_suma_s = new javax.swing.JLabel();
        lei_s = new javax.swing.JLabel();
        descriere_standard = new javax.swing.JTextArea();
        abonament_premium = new javax.swing.JPanel();
        label_premium = new javax.swing.JLabel();
        label_pret_p = new javax.swing.JLabel();
        label_suma_p = new javax.swing.JLabel();
        lei_p = new javax.swing.JLabel();
        descriere_premium = new javax.swing.JTextArea();
        backcrearecont = new javax.swing.JPanel();
        buton_backcrearecont = new javax.swing.JButton();
        nextplati = new javax.swing.JPanel();
        buton_nextplati = new javax.swing.JButton();
        alegere_abonament = new javax.swing.JComboBox<>();
        mesaj_err_abonament = new javax.swing.JTextField();
        inregistrare_utilizator = new javax.swing.JPanel();
        crearecont = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nume = new javax.swing.JTextField();
        sep_nume = new javax.swing.JSeparator();
        prenume = new javax.swing.JTextField();
        sep_prenume = new javax.swing.JSeparator();
        tara = new javax.swing.JTextField();
        sep_tara = new javax.swing.JSeparator();
        adresa = new javax.swing.JTextField();
        sep_adresa = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        sep_email = new javax.swing.JSeparator();
        parola = new javax.swing.JPasswordField();
        sep_parola = new javax.swing.JSeparator();
        datadenastere = new com.toedter.calendar.JDateChooser();
        backlogin = new javax.swing.JPanel();
        buton_back = new javax.swing.JButton();
        nextabonamente = new javax.swing.JPanel();
        buton_nextabonamente = new javax.swing.JButton();
        icon_nume = new javax.swing.JLabel();
        icon_prenume = new javax.swing.JLabel();
        icon_tara = new javax.swing.JLabel();
        icon_adresa = new javax.swing.JLabel();
        icon_email = new javax.swing.JLabel();
        icon_parola = new javax.swing.JLabel();
        icon_data = new javax.swing.JLabel();
        atentie = new javax.swing.JPanel();
        atentie_mesaj = new javax.swing.JLabel();
        icon_atentie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        baraXMinMax.setBackground(new java.awt.Color(0, 0, 0));
        baraXMinMax.setPreferredSize(new java.awt.Dimension(900, 30));
        baraXMinMax.setLayout(new java.awt.BorderLayout());

        iconXMinMax.setBackground(new java.awt.Color(0, 0, 0));
        iconXMinMax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonX.setBackground(new java.awt.Color(0, 0, 0));
        butonX.setName("X"); // NOI18N
        butonX.setPreferredSize(new java.awt.Dimension(30, 30));
        butonX.setLayout(new java.awt.BorderLayout());

        Xmouse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Xmouse.setForeground(new java.awt.Color(102, 102, 102));
        Xmouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Xmouse.setText("X");
        Xmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XmouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XmouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XmouseMouseExited(evt);
            }
        });
        butonX.add(Xmouse, java.awt.BorderLayout.CENTER);

        iconXMinMax.add(butonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        butonMax.setBackground(new java.awt.Color(0, 0, 0));
        butonMax.setPreferredSize(new java.awt.Dimension(30, 30));
        butonMax.setLayout(new java.awt.BorderLayout());

        Maxmouse.setForeground(new java.awt.Color(102, 102, 102));
        Maxmouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maxmouse.setText("⬜");
        Maxmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxmouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaxmouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaxmouseMouseExited(evt);
            }
        });
        butonMax.add(Maxmouse, java.awt.BorderLayout.CENTER);

        iconXMinMax.add(butonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        butonMin.setBackground(new java.awt.Color(0, 0, 0));
        butonMin.setPreferredSize(new java.awt.Dimension(30, 30));
        butonMin.setLayout(new java.awt.BorderLayout());

        Minmouse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Minmouse.setForeground(new java.awt.Color(102, 102, 102));
        Minmouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minmouse.setText("_");
        Minmouse.setToolTipText("");
        Minmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinmouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinmouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinmouseMouseExited(evt);
            }
        });
        butonMin.add(Minmouse, java.awt.BorderLayout.CENTER);

        iconXMinMax.add(butonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        baraXMinMax.add(iconXMinMax, java.awt.BorderLayout.EAST);

        getContentPane().add(baraXMinMax, java.awt.BorderLayout.PAGE_START);

        inregistrareUser.setBackground(new java.awt.Color(0, 0, 0));
        inregistrareUser.setPreferredSize(new java.awt.Dimension(900, 400));
        inregistrareUser.setLayout(new java.awt.BorderLayout());

        backgroundL.setPreferredSize(new java.awt.Dimension(800, 542));

        imag.setBackground(new java.awt.Color(220, 20, 60));
        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/google-play-movies-tv.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLLayout = new javax.swing.GroupLayout(backgroundL);
        backgroundL.setLayout(backgroundLLayout);
        backgroundLLayout.setHorizontalGroup(
            backgroundLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(imag, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        backgroundLLayout.setVerticalGroup(
            backgroundLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imag, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );

        inregistrareUser.add(backgroundL, java.awt.BorderLayout.WEST);

        backgroundR.setBackground(new java.awt.Color(0, 0, 0));
        backgroundR.setLayout(new java.awt.BorderLayout());

        inregistrare_abonamente_plati.setBackground(new java.awt.Color(220, 20, 60));
        inregistrare_abonamente_plati.setForeground(new java.awt.Color(255, 255, 255));
        inregistrare_abonamente_plati.setPreferredSize(new java.awt.Dimension(500, 633));
        inregistrare_abonamente_plati.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plati.setBackground(new java.awt.Color(220, 20, 60));
        plati.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plata_abonament.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        plata_abonament.setForeground(new java.awt.Color(255, 255, 255));
        plata_abonament.setText("Plata Abonament");
        plati.add(plata_abonament, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 320, 41));

        backcabonamente.setBackground(new java.awt.Color(0, 0, 0));
        backcabonamente.setLayout(new java.awt.BorderLayout());

        buton_backcabonamente.setBackground(new java.awt.Color(0, 0, 0));
        buton_backcabonamente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buton_backcabonamente.setForeground(new java.awt.Color(220, 20, 60));
        buton_backcabonamente.setText("Back");
        buton_backcabonamente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buton_backcabonamente.setBorderPainted(false);
        buton_backcabonamente.setContentAreaFilled(false);
        buton_backcabonamente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buton_backcabonamente.setFocusPainted(false);
        buton_backcabonamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_backcabonamenteActionPerformed(evt);
            }
        });
        backcabonamente.add(buton_backcabonamente, java.awt.BorderLayout.CENTER);

        plati.add(backcabonamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 170, 40));

        cont_inregistrat.setBackground(new java.awt.Color(255, 255, 255));
        cont_inregistrat.setLayout(new java.awt.BorderLayout());

        buton_inregistrare.setBackground(new java.awt.Color(255, 255, 255));
        buton_inregistrare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buton_inregistrare.setForeground(new java.awt.Color(220, 20, 60));
        buton_inregistrare.setText("Creare Cont");
        buton_inregistrare.setBorder(null);
        buton_inregistrare.setBorderPainted(false);
        buton_inregistrare.setContentAreaFilled(false);
        buton_inregistrare.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buton_inregistrare.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        buton_inregistrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_inregistrareActionPerformed(evt);
            }
        });
        cont_inregistrat.add(buton_inregistrare, java.awt.BorderLayout.CENTER);

        plati.add(cont_inregistrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 170, 40));

        text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setText("Ati ales abonamentul: ");
        plati.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        text2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setText("Doriti efectuarea platii in valoare de:");
        plati.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        copie_suma.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        copie_suma.setForeground(new java.awt.Color(255, 255, 255));
        plati.add(copie_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 140, 110));

        rb_nu.setBackground(new java.awt.Color(220, 20, 60));
        raspuns_plata.add(rb_nu);
        rb_nu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb_nu.setForeground(new java.awt.Color(255, 255, 255));
        rb_nu.setText("NU");
        rb_nu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        plati.add(rb_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        rb_da.setBackground(new java.awt.Color(220, 20, 60));
        raspuns_plata.add(rb_da);
        rb_da.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb_da.setForeground(new java.awt.Color(255, 255, 255));
        rb_da.setText("DA");
        rb_da.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        plati.add(rb_da, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        copie_abonament.setBackground(new java.awt.Color(252, 250, 250));
        copie_abonament.setForeground(new java.awt.Color(255, 242, 242));
        copie_abonament.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        copie_tip.setBackground(new java.awt.Color(255, 255, 255));
        copie_tip.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        copie_tip.setForeground(new java.awt.Color(0, 0, 0));
        copie_tip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copie_abonament.add(copie_tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 40));

        copie_pret.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        copie_pret.setForeground(new java.awt.Color(0, 0, 0));
        copie_pret.setText("Pret/luna");
        copie_abonament.add(copie_pret, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        copie_plataluna.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        copie_plataluna.setForeground(new java.awt.Color(220, 20, 60));
        copie_abonament.add(copie_plataluna, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, 30));

        copie_lei.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copie_lei.setForeground(new java.awt.Color(220, 20, 60));
        copie_lei.setText("Lei");
        copie_abonament.add(copie_lei, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 20));

        copie_descriere.setEditable(false);
        copie_descriere.setBackground(new java.awt.Color(252, 250, 250));
        copie_descriere.setColumns(4);
        copie_descriere.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        copie_descriere.setForeground(new java.awt.Color(220, 20, 60));
        copie_descriere.setRows(4);
        copie_descriere.setTabSize(20);
        copie_descriere.setBorder(null);
        copie_descriere.setCaretColor(new java.awt.Color(252, 250, 250));
        copie_descriere.setDisabledTextColor(new java.awt.Color(220, 20, 60));
        copie_descriere.setOpaque(false);
        copie_abonament.add(copie_descriere, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 80));

        plati.add(copie_abonament, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 220, 410, 120));

        mesaj_err_plata.setBackground(new java.awt.Color(220, 20, 60));
        mesaj_err_plata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mesaj_err_plata.setForeground(new java.awt.Color(255, 255, 255));
        mesaj_err_plata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mesaj_err_plata.setText("Te rugam sa alegi o optiune.");
        mesaj_err_plata.setBorder(null);
        mesaj_err_plata.setOpaque(true);
        plati.add(mesaj_err_plata, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 260, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lei");
        plati.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        inregistrare_abonamente_plati.add(plati, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 860));

        abonamente.setBackground(new java.awt.Color(220, 20, 60));
        abonamente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alegeabonament.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        alegeabonament.setForeground(new java.awt.Color(255, 255, 255));
        alegeabonament.setText("Abonamente");
        abonamente.add(alegeabonament, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, 41));

        abonament_basic.setBackground(new java.awt.Color(252, 250, 250));
        abonament_basic.setForeground(new java.awt.Color(255, 242, 242));
        abonament_basic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_basic.setBackground(new java.awt.Color(255, 255, 255));
        label_basic.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_basic.setForeground(new java.awt.Color(0, 0, 0));
        label_basic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abonament_basic.add(label_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        label_pret_b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_pret_b.setForeground(new java.awt.Color(0, 0, 0));
        label_pret_b.setText("Pret/luna");
        abonament_basic.add(label_pret_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        label_suma_b.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        label_suma_b.setForeground(new java.awt.Color(220, 20, 60));
        abonament_basic.add(label_suma_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, 30));

        lei_b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lei_b.setForeground(new java.awt.Color(220, 20, 60));
        lei_b.setText("Lei");
        abonament_basic.add(lei_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 20));

        descriere_basic.setEditable(false);
        descriere_basic.setBackground(new java.awt.Color(252, 250, 250));
        descriere_basic.setColumns(4);
        descriere_basic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        descriere_basic.setForeground(new java.awt.Color(220, 20, 60));
        descriere_basic.setRows(4);
        descriere_basic.setTabSize(20);
        descriere_basic.setBorder(null);
        descriere_basic.setCaretColor(new java.awt.Color(252, 250, 250));
        descriere_basic.setDisabledTextColor(new java.awt.Color(220, 20, 60));
        descriere_basic.setOpaque(false);
        abonament_basic.add(descriere_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 80));

        abonamente.add(abonament_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 410, 120));

        abonament_standard.setBackground(new java.awt.Color(252, 250, 250));
        abonament_standard.setForeground(new java.awt.Color(255, 242, 242));
        abonament_standard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_standard.setBackground(new java.awt.Color(255, 255, 255));
        label_standard.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_standard.setForeground(new java.awt.Color(0, 0, 0));
        label_standard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abonament_standard.add(label_standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        label_pret_s.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_pret_s.setForeground(new java.awt.Color(0, 0, 0));
        label_pret_s.setText("Pret/luna");
        abonament_standard.add(label_pret_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        label_suma_s.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        label_suma_s.setForeground(new java.awt.Color(220, 20, 60));
        abonament_standard.add(label_suma_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, 30));

        lei_s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lei_s.setForeground(new java.awt.Color(220, 20, 60));
        lei_s.setText("Lei");
        abonament_standard.add(lei_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        descriere_standard.setEditable(false);
        descriere_standard.setBackground(new java.awt.Color(252, 250, 250));
        descriere_standard.setColumns(1);
        descriere_standard.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        descriere_standard.setForeground(new java.awt.Color(220, 20, 60));
        descriere_standard.setRows(4);
        descriere_standard.setTabSize(20);
        descriere_standard.setBorder(null);
        descriere_standard.setDisabledTextColor(new java.awt.Color(220, 20, 60));
        abonament_standard.add(descriere_standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 80));

        abonamente.add(abonament_standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 410, 120));

        abonament_premium.setBackground(new java.awt.Color(252, 250, 250));
        abonament_premium.setForeground(new java.awt.Color(255, 242, 242));
        abonament_premium.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_premium.setBackground(new java.awt.Color(255, 255, 255));
        label_premium.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_premium.setForeground(new java.awt.Color(0, 0, 0));
        label_premium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abonament_premium.add(label_premium, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        label_pret_p.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_pret_p.setForeground(new java.awt.Color(0, 0, 0));
        label_pret_p.setText("Pret/luna");
        abonament_premium.add(label_pret_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        label_suma_p.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        label_suma_p.setForeground(new java.awt.Color(220, 20, 60));
        abonament_premium.add(label_suma_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, 30));

        lei_p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lei_p.setForeground(new java.awt.Color(220, 20, 60));
        lei_p.setText("Lei");
        abonament_premium.add(lei_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        descriere_premium.setEditable(false);
        descriere_premium.setBackground(new java.awt.Color(252, 250, 250));
        descriere_premium.setColumns(1);
        descriere_premium.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        descriere_premium.setForeground(new java.awt.Color(220, 20, 60));
        descriere_premium.setRows(4);
        descriere_premium.setTabSize(20);
        descriere_premium.setBorder(null);
        descriere_premium.setDisabledTextColor(new java.awt.Color(220, 20, 60));
        abonament_premium.add(descriere_premium, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 80));

        abonamente.add(abonament_premium, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 410, 120));

        backcrearecont.setBackground(new java.awt.Color(0, 0, 0));
        backcrearecont.setLayout(new java.awt.BorderLayout());

        buton_backcrearecont.setBackground(new java.awt.Color(0, 0, 0));
        buton_backcrearecont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buton_backcrearecont.setForeground(new java.awt.Color(220, 20, 60));
        buton_backcrearecont.setText("Back");
        buton_backcrearecont.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buton_backcrearecont.setBorderPainted(false);
        buton_backcrearecont.setContentAreaFilled(false);
        buton_backcrearecont.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buton_backcrearecont.setFocusPainted(false);
        buton_backcrearecont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_backcrearecontActionPerformed(evt);
            }
        });
        backcrearecont.add(buton_backcrearecont, java.awt.BorderLayout.CENTER);

        abonamente.add(backcrearecont, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 170, 40));

        nextplati.setBackground(new java.awt.Color(255, 255, 255));
        nextplati.setLayout(new java.awt.BorderLayout());

        buton_nextplati.setBackground(new java.awt.Color(255, 255, 255));
        buton_nextplati.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buton_nextplati.setForeground(new java.awt.Color(220, 20, 60));
        buton_nextplati.setText("Next");
        buton_nextplati.setBorder(null);
        buton_nextplati.setBorderPainted(false);
        buton_nextplati.setContentAreaFilled(false);
        buton_nextplati.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buton_nextplati.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        buton_nextplati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_nextplatiActionPerformed(evt);
            }
        });
        nextplati.add(buton_nextplati, java.awt.BorderLayout.CENTER);

        abonamente.add(nextplati, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 170, 40));

        alegere_abonament.setBackground(new java.awt.Color(255, 255, 255));
        alegere_abonament.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alegere_abonament.setForeground(new java.awt.Color(0, 0, 0));
        alegere_abonament.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Alege Abonament---", "Basic", "Standard", "Premium" }));
        alegere_abonament.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        alegere_abonament.setLightWeightPopupEnabled(false);
        alegere_abonament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alegere_abonamentActionPerformed(evt);
            }
        });
        abonamente.add(alegere_abonament, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 150, 30));

        mesaj_err_abonament.setBackground(new java.awt.Color(220, 20, 60));
        mesaj_err_abonament.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mesaj_err_abonament.setForeground(new java.awt.Color(255, 255, 255));
        mesaj_err_abonament.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mesaj_err_abonament.setText("Trebuie sa alegi o optiune.\n");
        mesaj_err_abonament.setBorder(null);
        mesaj_err_abonament.setOpaque(true);
        abonamente.add(mesaj_err_abonament, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 410, 30));

        inregistrare_abonamente_plati.add(abonamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 860));

        inregistrare_utilizator.setBackground(new java.awt.Color(220, 20, 60));
        inregistrare_utilizator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearecont.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        crearecont.setForeground(new java.awt.Color(255, 255, 255));
        crearecont.setText("Creare Cont");
        inregistrare_utilizator.add(crearecont, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, 41));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(220, 20, 60));
        jTextField1.setBorder(null);
        inregistrare_utilizator.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 10, 10));

        nume.setBackground(new java.awt.Color(220, 20, 60));
        nume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nume.setForeground(new java.awt.Color(255, 255, 255));
        nume.setText("Nume");
        nume.setBorder(null);
        nume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeFocusLost(evt);
            }
        });
        inregistrare_utilizator.add(nume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 360, 30));

        sep_nume.setBackground(new java.awt.Color(51, 0, 51));
        sep_nume.setForeground(new java.awt.Color(51, 0, 51));
        sep_nume.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        inregistrare_utilizator.add(sep_nume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 360, 2));

        prenume.setBackground(new java.awt.Color(220, 20, 60));
        prenume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prenume.setForeground(new java.awt.Color(255, 255, 255));
        prenume.setText("Prenume");
        prenume.setBorder(null);
        prenume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prenumeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prenumeFocusLost(evt);
            }
        });
        inregistrare_utilizator.add(prenume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 360, 30));

        sep_prenume.setBackground(new java.awt.Color(51, 0, 51));
        sep_prenume.setForeground(new java.awt.Color(51, 0, 51));
        sep_prenume.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        inregistrare_utilizator.add(sep_prenume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 360, 2));

        tara.setBackground(new java.awt.Color(220, 20, 60));
        tara.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tara.setForeground(new java.awt.Color(255, 255, 255));
        tara.setText("Tara");
        tara.setBorder(null);
        tara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                taraFocusLost(evt);
            }
        });
        inregistrare_utilizator.add(tara, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 360, 30));

        sep_tara.setBackground(new java.awt.Color(51, 0, 51));
        sep_tara.setForeground(new java.awt.Color(51, 0, 51));
        sep_tara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        inregistrare_utilizator.add(sep_tara, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 360, 2));

        adresa.setBackground(new java.awt.Color(220, 20, 60));
        adresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adresa.setForeground(new java.awt.Color(255, 255, 255));
        adresa.setText("Adresa");
        adresa.setBorder(null);
        adresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adresaFocusLost(evt);
            }
        });
        inregistrare_utilizator.add(adresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 360, 30));

        sep_adresa.setBackground(new java.awt.Color(51, 0, 51));
        sep_adresa.setForeground(new java.awt.Color(51, 0, 51));
        sep_adresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        inregistrare_utilizator.add(sep_adresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 360, 2));

        email.setBackground(new java.awt.Color(220, 20, 60));
        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-mail");
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        inregistrare_utilizator.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 360, 30));

        sep_email.setBackground(new java.awt.Color(51, 0, 51));
        sep_email.setForeground(new java.awt.Color(51, 0, 51));
        sep_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        inregistrare_utilizator.add(sep_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 360, 2));

        parola.setBackground(new java.awt.Color(220, 20, 60));
        parola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parola.setForeground(new java.awt.Color(255, 255, 255));
        parola.setText("Password");
        parola.setBorder(null);
        parola.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                parolaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                parolaFocusLost(evt);
            }
        });
        inregistrare_utilizator.add(parola, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 360, 30));

        sep_parola.setBackground(new java.awt.Color(51, 0, 51));
        sep_parola.setForeground(new java.awt.Color(51, 0, 51));
        sep_parola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        inregistrare_utilizator.add(sep_parola, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 360, 2));

        datadenastere.setBackground(new java.awt.Color(220, 20, 60));
        datadenastere.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Data de nastere", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        datadenastere.setForeground(new java.awt.Color(51, 0, 51));
        datadenastere.setToolTipText("yyyy-MM-dd");
        datadenastere.setAutoscrolls(true);
        datadenastere.setDateFormatString("yyyy-MM-dd");
        datadenastere.setDoubleBuffered(false);
        datadenastere.setOpaque(false);
        inregistrare_utilizator.add(datadenastere, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 280, 60));

        backlogin.setBackground(new java.awt.Color(0, 0, 0));
        backlogin.setLayout(new java.awt.BorderLayout());

        buton_back.setBackground(new java.awt.Color(0, 0, 0));
        buton_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buton_back.setForeground(new java.awt.Color(220, 20, 60));
        buton_back.setText("Back");
        buton_back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buton_back.setBorderPainted(false);
        buton_back.setContentAreaFilled(false);
        buton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buton_back.setFocusPainted(false);
        buton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_backActionPerformed(evt);
            }
        });
        backlogin.add(buton_back, java.awt.BorderLayout.CENTER);

        inregistrare_utilizator.add(backlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 170, 40));

        nextabonamente.setBackground(new java.awt.Color(255, 255, 255));
        nextabonamente.setLayout(new java.awt.BorderLayout());

        buton_nextabonamente.setBackground(new java.awt.Color(255, 255, 255));
        buton_nextabonamente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buton_nextabonamente.setForeground(new java.awt.Color(220, 20, 60));
        buton_nextabonamente.setText("Next");
        buton_nextabonamente.setBorder(null);
        buton_nextabonamente.setBorderPainted(false);
        buton_nextabonamente.setContentAreaFilled(false);
        buton_nextabonamente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buton_nextabonamente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        buton_nextabonamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_nextabonamenteActionPerformed(evt);
            }
        });
        nextabonamente.add(buton_nextabonamente, java.awt.BorderLayout.CENTER);

        inregistrare_utilizator.add(nextabonamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 170, 40));

        icon_nume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user (2).png"))); // NOI18N
        inregistrare_utilizator.add(icon_nume, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        icon_prenume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user (2).png"))); // NOI18N
        inregistrare_utilizator.add(icon_prenume, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        icon_tara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/coronavirus (1).png"))); // NOI18N
        inregistrare_utilizator.add(icon_tara, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 30, 30));

        icon_adresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pin (1).png"))); // NOI18N
        inregistrare_utilizator.add(icon_adresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 30));

        icon_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/email (1).png"))); // NOI18N
        inregistrare_utilizator.add(icon_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 30));

        icon_parola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock (1).png"))); // NOI18N
        inregistrare_utilizator.add(icon_parola, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 30));

        icon_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar.png"))); // NOI18N
        inregistrare_utilizator.add(icon_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 40));

        atentie.setOpaque(false);
        atentie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atentie_mesaj.setBackground(new java.awt.Color(220, 20, 60));
        atentie_mesaj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atentie_mesaj.setForeground(new java.awt.Color(255, 255, 255));
        atentie_mesaj.setText("Toate campurile trebuie completate.");
        atentie_mesaj.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        atentie.add(atentie_mesaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 40));

        icon_atentie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exclamation_24.png"))); // NOI18N
        icon_atentie.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        icon_atentie.setFocusable(false);
        icon_atentie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        atentie.add(icon_atentie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        inregistrare_utilizator.add(atentie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 290, 40));

        inregistrare_abonamente_plati.add(inregistrare_utilizator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 780));

        backgroundR.add(inregistrare_abonamente_plati, java.awt.BorderLayout.WEST);

        inregistrareUser.add(backgroundR, java.awt.BorderLayout.CENTER);

        getContentPane().add(inregistrareUser, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1362, 891));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void changecolor(Panel fundal, Color rand){
           fundal.setBackground(rand);
    }
    
    private void XmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XmouseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XmouseMouseClicked

    private void XmouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XmouseMouseEntered
        changecolor(butonX, new Color(128,0,0));
    }//GEN-LAST:event_XmouseMouseEntered

    private void XmouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XmouseMouseExited
        changecolor(butonX, new Color(0,0,0));
    }//GEN-LAST:event_XmouseMouseExited

    private void MaxmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxmouseMouseClicked
        if (this.getExtendedState() != MAXIMIZED_BOTH){
            this.setExtendedState(MAXIMIZED_BOTH);
        }
        else this.setExtendedState(NORMAL);
    }//GEN-LAST:event_MaxmouseMouseClicked

    private void MaxmouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxmouseMouseEntered
        changecolor(butonMax, new Color(128,0,0));
    }//GEN-LAST:event_MaxmouseMouseEntered

    private void MaxmouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxmouseMouseExited
        changecolor(butonMax, new Color(0,0,0));
    }//GEN-LAST:event_MaxmouseMouseExited

    private void MinmouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinmouseMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_MinmouseMouseClicked

    private void MinmouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinmouseMouseEntered
        changecolor(butonMin, new Color(128,0,0));
    }//GEN-LAST:event_MinmouseMouseEntered

    private void MinmouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinmouseMouseExited
        changecolor(butonMin, new Color(0,0,0));
    }//GEN-LAST:event_MinmouseMouseExited

    private void numeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeFocusGained
        String numeVal = nume.getText();
        
        if(numeVal.equals("Nume") || numeVal.equals(""))
            nume.setText("");
        else nume.setText(numeVal);
    }//GEN-LAST:event_numeFocusGained

    private void prenumeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenumeFocusGained
     String numeVal = prenume.getText();
        
      if(numeVal.equals("Prenume") || numeVal.equals(""))
         prenume.setText("");
     else prenume.setText(numeVal);
    }//GEN-LAST:event_prenumeFocusGained

    private void taraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taraFocusGained
        String numeVal = tara.getText();
        
        if(numeVal.equals("Tara") || numeVal.equals(""))
            tara.setText("");
        else tara.setText(numeVal);
    }//GEN-LAST:event_taraFocusGained

    private void adresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresaFocusGained
         String numeVal = adresa.getText();
        
        if(numeVal.equals("Adresa") || numeVal.equals(""))
            adresa.setText("");
        else adresa.setText(numeVal);
    }//GEN-LAST:event_adresaFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        String numeVal = email.getText();
        
        if(numeVal.equals("E-mail") || numeVal.equals(""))
            email.setText("");
        else email.setText(numeVal);
    }//GEN-LAST:event_emailFocusGained

    private void parolaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parolaFocusGained
        String numeVal = String.valueOf(parola.getPassword());;
        
        if(numeVal.equals("Password") || numeVal.equals(""))
            parola.setText("");
        else parola.setText(numeVal);
    }//GEN-LAST:event_parolaFocusGained

    private void numeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeFocusLost
        String numeVal = nume.getText();
        
        if(numeVal.equals("Nume") || numeVal.equals(""))
            nume.setText("Nume");
        else nume.setText(numeVal);
    }//GEN-LAST:event_numeFocusLost

    private void prenumeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenumeFocusLost
        String numeVal = prenume.getText();
        
        if(numeVal.equals("Prenume") || numeVal.equals(""))
            prenume.setText("Prenume");
        else prenume.setText(numeVal);
    }//GEN-LAST:event_prenumeFocusLost

    private void taraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taraFocusLost
        String numeVal = tara.getText();
        
        if(numeVal.equals("Tara") || numeVal.equals(""))
            tara.setText("Tara");
        else tara.setText(numeVal);
    }//GEN-LAST:event_taraFocusLost

    private void adresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresaFocusLost
        String numeVal = adresa.getText();
        
        if(numeVal.equals("Adresa") || numeVal.equals(""))
            adresa.setText("Adresa");
        else adresa.setText(numeVal);
    }//GEN-LAST:event_adresaFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        String numeVal = email.getText();
        
        if(numeVal.equals("E-mail") || numeVal.equals(""))
            email.setText("E-mail");
        else email.setText(numeVal);
    }//GEN-LAST:event_emailFocusLost

    private void parolaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parolaFocusLost
        String numeVal = String.valueOf(parola.getPassword());
        
        if(numeVal.equals("Password") || numeVal.equals(""))
            parola.setText("Password");
        else parola.setText(numeVal);
    }//GEN-LAST:event_parolaFocusLost

    private void buton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_backActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buton_backActionPerformed

    private void buton_nextabonamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_nextabonamenteActionPerformed
      
        String numeU = nume.getText();
        String prenumeU = prenume.getText();
        String taraU = tara.getText();
        String adresaU = adresa.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        String datanasteriiU = dateFormat.format(datadenastere.getDate());
        String emailU = email.getText();
        String parolaU = String.valueOf(parola.getPassword());
       
            if(numeU.equals("Nume") || prenumeU.equals("Prenume") || taraU.equals("Tara") || adresaU.equals("Adresa") || emailU.equals("E-mail") || parolaU.equals("Password")){
                 atentie.setVisible(true);
            }
            else {
                try {

                    Connection con = ConectareBD.bdConectare();
                    Statement stm = con.createStatement();
                    //String insert = "insert into utilizator(nume, prenume, tara, adresa, datanasterii, email, parola) values('"+numeU+"', '"+prenumeU+"', '"+taraU+"', '"+adresaU+"', '"+datanasteriiU+"','"+emailU+"', '"+parolaU+"');";
                    //stm.executeUpdate(insert);
                    //JOptionPane.showMessageDialog(null, "Succes");
                    
                    abonamente.setVisible(true);
                    inregistrare_utilizator.setVisible(false);
                    
                    for(int i = 1; i <= 3;  i++){
                        String select = "select * from abonament where abonamentID = '"+i+"';";
                        ResultSet rs = stm.executeQuery(select);
                        
                        if(rs.next()){
                            String tip_a = rs.getString(2);
                            String suma_a = rs.getString(4);
                            String descriere_a = rs.getString(3);
                            
                            if(i == 1){
                                label_basic.setText(tip_a);
                                label_suma_b.setText(suma_a);
                                descriere_basic.setText(descriere_a);
                                descriere_basic.setLineWrap(true);
                                descriere_basic.setWrapStyleWord(true);
                            }
                            else if(i == 2){
                                label_standard.setText(tip_a);
                                label_suma_s.setText(suma_a);
                                descriere_standard.setText(descriere_a);
                                descriere_standard.setLineWrap(true);
                                descriere_standard.setWrapStyleWord(true);
                            }
                            else{
                                label_premium.setText(tip_a);
                                label_suma_p.setText(suma_a);
                                descriere_premium.setText(descriere_a);
                                descriere_premium.setLineWrap(true);
                                descriere_premium.setWrapStyleWord(true);
                            } 
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Erore pentru "+i+"");    
                    }
                    con.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Not Succes");
                }
              
            }
        
    }//GEN-LAST:event_buton_nextabonamenteActionPerformed

    private void buton_backcrearecontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_backcrearecontActionPerformed
        inregistrare_utilizator.setVisible(true);
        abonamente.setVisible(false);
    }//GEN-LAST:event_buton_backcrearecontActionPerformed

    private void buton_nextplatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_nextplatiActionPerformed
      String valSelectata = alegere_abonament.getSelectedItem().toString();
        
      if(valSelectata == "---Alege Abonament---"){
             mesaj_err_abonament.setVisible(true);
      }
      else{
        try {
            Connection con = ConectareBD.bdConectare(); 
            Statement stm = con.createStatement();
            
            for(int i = 0; i <= 3; i++){
                String select = "select * from abonament where abonamentID = '"+i+"';";
                ResultSet rs = stm.executeQuery(select);
                        
                if(rs.next()){
                    String tip_a = rs.getString(2);
                    String suma_a = rs.getString(4);
                    String descriere_a = rs.getString(3);
                    //System.out.print(tip_a + " " + suma_a + " " + descriere_a);
                    
                    if(tip_a.equals(valSelectata)){
                        copie_tip.setText(tip_a);
                        copie_plataluna.setText(suma_a);
                        copie_descriere.setText(descriere_a);
                        copie_descriere.setLineWrap(true);
                        copie_descriere.setWrapStyleWord(true);
                        copie_suma.setText(suma_a);
                        //String insert = "insert into utilizator(abonamentId) values('"+rs.getInt(1)+"');";
                        
                        plati.setVisible(true);
                        abonamente.setVisible(false);
                    }
                    else System.out.println("Nu s-a facut selectia");
                } 
             }
            con.close();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Not Succes");
        }
      }
        
              
        /*if(valSelectata == "BASIC"){ 
             copie_abonament.add(label_basic); 
             copie_abonament.add(label_pret_b);
             copie_abonament.add(label_suma_b);
             copie_abonament.add(lei_b);
             copie_abonament.add(descriere_basic);
             
             copie_suma.setText("39.99 lei");
         }
         
         if(valSelectata == "STANDARD"){ 
             copie_abonament.add(label_standard); 
             copie_abonament.add(label_pret_s);
             copie_abonament.add(label_suma_s);
             copie_abonament.add(lei_s);
             copie_abonament.add(descriere_standard);
             
             copie_suma.setText("49.99 lei");
         }
         
         if(valSelectata == "PREMIUM"){ 
             copie_abonament.add(label_premium); 
             copie_abonament.add(label_pret_p);
             copie_abonament.add(label_suma_p);
             copie_abonament.add(lei_p);
             copie_abonament.add(descriere_premium);
             
             copie_suma.setText("59.99 lei");
         }*/   
    }//GEN-LAST:event_buton_nextplatiActionPerformed

    private void buton_backcabonamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_backcabonamenteActionPerformed
        abonamente.setVisible(true);
        plati.setVisible(false);
    }//GEN-LAST:event_buton_backcabonamenteActionPerformed

    private void buton_inregistrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_inregistrareActionPerformed
       
        String numeU = nume.getText();
        String prenumeU = prenume.getText();
        String taraU = tara.getText();
        String adresaU = adresa.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        String datanasteriiU = dateFormat.format(datadenastere.getDate());
        String emailU = email.getText();
        String parolaU = String.valueOf(parola.getPassword());
        String valSelectata = alegere_abonament.getSelectedItem().toString();
       
        //System.out.print(numeU);
        try {
            Connection con = ConectareBD.bdConectare();
            Statement stm = con.createStatement();
                    
            
            for(int i = 0; i < 3; i++){
                int id_a = i + 1;
                String select_a = "select * from abonament where abonamentID = '"+id_a+"';";
                ResultSet rs_a = stm.executeQuery(select_a);
                        
                if(rs_a.next()){
                    String tip_a = rs_a.getString(2);
                                
                    if(tip_a.equals(valSelectata)){
                        
                        //String insert = "insert into utilizator(abonamentId) values('"+rs.getInt(1)+"');";
                        rb_da.isSelected();
                        rb_nu.isSelected();
       
                        if(rb_da.isSelected()){
                            java.util.Date utilDate = new java.util.Date();
                            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                            //insert utilizator
                            String insert_u = "insert into utilizator(abonamentID, nume, prenume, tara, adresa, datanasterii, email, parola, dataAbonarii) values('"+rs_a.getInt(1)+"','"+numeU+"', '"+prenumeU+"', '"+taraU+"', '"+adresaU+"', '"+datanasteriiU+"','"+emailU+"', '"+parolaU+"','"+sqlDate+"');";
                            stm.executeUpdate(insert_u);
                            
                            
                           int id_u = -1; //obtinerea utilizatorID
                           ResultSet rs_u = stm.executeQuery("select LAST_INSERT_ID() from utilizator;");
                           if (rs_u.next()) {
                                id_u = rs_u.getInt(1);
                           } 
                           
                           float[] suma = new float[]{39.99f, 49.99f, 59.99f};
                           String status_p = "platit";
                           //insert plati
                           String insert_p = "insert into plati(utilizatorID, dataPlatii, sumaPlatita, status) values('"+id_u+"','"+sqlDate+"', '"+suma[i]+"', '"+status_p+"');";
                           stm.executeUpdate(insert_p);
                            
                           JOptionPane.showMessageDialog(null, "Succes");
                           new login().setVisible(true);
                           login.mesaj_da.setVisible(true);
                           rb_nu.setSelected(false);
                           setVisible(false);
                           plati.setVisible(false);
                        }
                        if(rb_nu.isSelected()){
                            JOptionPane.showMessageDialog(null, "Not Succes");
                            new login().setVisible(true);
                            login.mesaj_nu.setVisible(true);
                            rb_da.setSelected(false);
                            plati.setVisible(false);
                        }
                        else mesaj_err_plata.setVisible(true);
                        
                    }
                    else System.out.print("Ceva nu a mers bine ");
                } 
            }          
        con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Not Succes");
        }
          
    }//GEN-LAST:event_buton_inregistrareActionPerformed

    private void alegere_abonamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alegere_abonamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alegere_abonamentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inregistrare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Maxmouse;
    private javax.swing.JLabel Minmouse;
    private javax.swing.JLabel Xmouse;
    private javax.swing.JPanel abonament_basic;
    private javax.swing.JPanel abonament_premium;
    private javax.swing.JPanel abonament_standard;
    private javax.swing.JPanel abonamente;
    private javax.swing.JTextField adresa;
    private javax.swing.JLabel alegeabonament;
    private javax.swing.JComboBox<String> alegere_abonament;
    private javax.swing.JPanel atentie;
    private javax.swing.JLabel atentie_mesaj;
    private javax.swing.JPanel backcabonamente;
    private javax.swing.JPanel backcrearecont;
    private java.awt.Panel backgroundL;
    private java.awt.Panel backgroundR;
    private javax.swing.JPanel backlogin;
    private java.awt.Panel baraXMinMax;
    private java.awt.Panel butonMax;
    private java.awt.Panel butonMin;
    private java.awt.Panel butonX;
    private javax.swing.JButton buton_back;
    private javax.swing.JButton buton_backcabonamente;
    private javax.swing.JButton buton_backcrearecont;
    private javax.swing.JButton buton_inregistrare;
    private javax.swing.JButton buton_nextabonamente;
    private javax.swing.JButton buton_nextplati;
    private javax.swing.JPanel cont_inregistrat;
    private javax.swing.JPanel copie_abonament;
    private javax.swing.JTextArea copie_descriere;
    private javax.swing.JLabel copie_lei;
    private javax.swing.JLabel copie_plataluna;
    private javax.swing.JLabel copie_pret;
    private javax.swing.JLabel copie_suma;
    private javax.swing.JLabel copie_tip;
    private javax.swing.JLabel crearecont;
    private com.toedter.calendar.JDateChooser datadenastere;
    private javax.swing.JTextArea descriere_basic;
    private javax.swing.JTextArea descriere_premium;
    private javax.swing.JTextArea descriere_standard;
    private javax.swing.JTextField email;
    private java.awt.Panel iconXMinMax;
    private javax.swing.JLabel icon_adresa;
    private javax.swing.JLabel icon_atentie;
    private javax.swing.JLabel icon_data;
    private javax.swing.JLabel icon_email;
    private javax.swing.JLabel icon_nume;
    private javax.swing.JLabel icon_parola;
    private javax.swing.JLabel icon_prenume;
    private javax.swing.JLabel icon_tara;
    private javax.swing.JLabel imag;
    private java.awt.Panel inregistrareUser;
    private java.awt.Panel inregistrare_abonamente_plati;
    private javax.swing.JPanel inregistrare_utilizator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_basic;
    private javax.swing.JLabel label_premium;
    private javax.swing.JLabel label_pret_b;
    private javax.swing.JLabel label_pret_p;
    private javax.swing.JLabel label_pret_s;
    private javax.swing.JLabel label_standard;
    private javax.swing.JLabel label_suma_b;
    private javax.swing.JLabel label_suma_p;
    private javax.swing.JLabel label_suma_s;
    private javax.swing.JLabel lei_b;
    private javax.swing.JLabel lei_p;
    private javax.swing.JLabel lei_s;
    private javax.swing.JTextField mesaj_err_abonament;
    private javax.swing.JTextField mesaj_err_plata;
    private javax.swing.JPanel nextabonamente;
    private javax.swing.JPanel nextplati;
    private javax.swing.JTextField nume;
    private javax.swing.JPasswordField parola;
    private javax.swing.JLabel plata_abonament;
    private javax.swing.JPanel plati;
    private javax.swing.JTextField prenume;
    private javax.swing.ButtonGroup raspuns_plata;
    private javax.swing.JRadioButton rb_da;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JSeparator sep_adresa;
    private javax.swing.JSeparator sep_email;
    private javax.swing.JSeparator sep_nume;
    private javax.swing.JSeparator sep_parola;
    private javax.swing.JSeparator sep_prenume;
    private javax.swing.JSeparator sep_tara;
    private javax.swing.JTextField tara;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    // End of variables declaration//GEN-END:variables
}
